# Generated by Django 2.2.10 on 2022-07-10 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0003_auto_20220710_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
