# Generated by Django 2.2.10 on 2022-07-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20220710_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='criado_por',
        ),
    ]
