# Generated by Django 2.2.10 on 2022-07-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_paciente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='user',
            new_name='criador_por',
        ),
    ]
