# Generated by Django 2.2.10 on 2022-07-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_auto_20220710_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='criador_por',
        ),
    ]
