# Generated by Django 2.2.10 on 2022-07-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_auto_20220704_2035'),
        ('paciente', '0009_remove_paciente_criador_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='criador_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionario.Funcionario'),
            preserve_default=False,
        ),
    ]
