# Generated by Django 2.2.10 on 2022-07-10 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_paciente_criador_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='criador_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
