# Generated by Django 2.2.10 on 2022-07-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_auto_20220710_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='criado_em',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='paciente',
            name='entidade_patronal',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='paciente',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='paciente',
            name='etnia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fator_sanguino',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='mae',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pai',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
