# Generated by Django 2.2.10 on 2022-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_auto_20220704_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='contacto',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
